name: exposure
version: 1.0.4
description: >
  Sensor widget for flutter that notifies you when it is exposured
homepage: https://github.com/northka/exposure
dependencies:
  toast: ^0.1.4
  flutter:
    sdk: flutter
dev_dependencies:
  pedantic: 1.8.0+1
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.5.4-hotfix.2 <2.0.0"